[package]
name = "cargo-readme"
version = "1.3.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "A cargo subcommand to generate README.md content from doc comments"
repository = "https://github.com/livioribeiro/cargo-readme"
readme = "README.md"
keywords = ["readme", "documentation", "cargo", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = "2.0"
toml = "0.3"
regex = "0.2"
serde = "0.9"
serde_derive = "0.9"
