[package]
name = "cargo-readme"
version = "2.0.1"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "A cargo subcommand to generate README.md content from doc comments"
repository = "https://github.com/livioribeiro/cargo-readme"
readme = "README.md"
keywords = ["readme", "documentation", "cargo", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = "2.31"
toml = "0.4"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
percent-encoding = "1.0"

[dev-dependencies]
assert_cli = "0.6"

[badges]
appveyor = { repository = "livioribeiro/cargo-readme", service = "github" }
circle-ci = { repository = "livioribeiro/cargo-readme" }
travis-ci = { repository = "livioribeiro/cargo-readme" }