[package]
name = "cargo-readme"
version = "0.2.3"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "A cargo subcommand to generate README.md content from doc comments"
repository = "https://github.com/livioribeiro/cargo-readme"
readme = "README.md"
keywords = ["readme", "documentation", "cargo", "subcommand"]
license = "MIT OR Apache-2.0"
exclude = ["test-projects"]

[dependencies]
clap = "2.0"
toml = "0.1"
regex = "0.1"
rustc-serialize = "0.3"
